### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by pherjung**

### CODE REVIEW

**Comment by dcaliste** [comment]
Thanks @pherjung, as for @flaypig I'm giving you write access to this repo, so you can merge also yourself or add content if you feel so.

**Comment by llewelld** [comment]
I must admit, I thought you already did give me write access @dcaliste. I've been merrily pushing stuff to the repo I'm afraid, so apologies if I overstepped the mark.

I missed this PR though, so good that you pinged me. I've fixed this on the forum now too.

**Comment by dcaliste** [comment]
@flypig, my phrasing was inaccurate, you should have read something like "I'm giving you (pherjung) write access, as I've done it before to @flypig" ;)

**Comment by llewelld** [comment]
Ah, sorry! The problem wasn't your phrasing but my poor reading, but thank you for clarifying. And it's great to have you contributing directly @pherjung.

**Pull request merged**
