### PR TITLE
Tidyup repository roundup and add app roundup

### PR DESCRIPTION
**Pull request by llewelld**
These changes tidy up some of the text to match the formatting to be used in the final copy, and adds the app section.

The changes get a bit messed up when they're all diffed together, but are clearer at the level of the individual commits.

### CODE REVIEW

**Comment by llewelld** [comment]
I thought it would be interesting to try having the app section worked on in a slightly more open way as well.

**Comment by dcaliste** [comment]
Thank you @flypig for the addition and the formatting. I'll try to keep it for the next run.

Besides, I think it would be more efficient if I give you write permission to this repo, don't I ?

**Comment by llewelld** [comment]
> Besides, I think it would be more efficient if I give you write permission to this repo, don't I ?

Thank you for the invitation. I'm happy to work this way, or to commit directly as you prefer. It's not a bad thing to have someone else double check changes, but on the other hand I don't want it to be disruptive for you.

So, in future I'll commit directly to master, but if at any point you feel this isn't working, then of course let me know and I'll revert to submitting PRs.

**Comment by dcaliste** [comment]
Sure. I think the thing has to be reactive, and I'm not sure I can review PR quickly enough. These "news" parts are not very sensitive. I guess just committing directly to master should work. We can have a look to the commit of the other and still amend it later on if necessary.

**Pull request merged**
